#ifndef INC_GDCL_VERSION_H
#define INC_GDCL_VERSION_H

#define GDCL_VERSION  "@PROJECT_VERSION@"
#define GDCL_VERSION_MAJOR "@PROJECT_VERSION_MAJOR@"
#define GDCL_VERSION_MINOR "@PROJECT_VERSION_MINOR@"
#define GDCL_VERSION_PATCH "@PROJECT_VERSION_PATCH@"

#endif//INC_GDCL_VERSION_H