#ifndef INC_GDCL_GAME_ITEM_TYPE_H
#define INC_GDCL_GAME_ITEM_TYPE_H

#include <stdint.h>

enum ItemType : uint32_t
{
    ITEM_TYPE_OTHER = 0,
    ITEM_TYPE_HEAD = 1,
    ITEM_TYPE_AMULET = 2,
    ITEM_TYPE_CHEST = 3,
    ITEM_TYPE_LEGS = 4,
    ITEM_TYPE_FEET = 5,
    ITEM_TYPE_RING = 6,
    ITEM_TYPE_HANDS = 7,
    ITEM_TYPE_BELT = 8,
    ITEM_TYPE_SHOULDERS = 9,
    ITEM_TYPE_MEDAL = 10,
    ITEM_TYPE_SWORD_1H = 11,
    ITEM_TYPE_SWORD_2H = 12,
    ITEM_TYPE_AXE_1H = 13,
    ITEM_TYPE_AXE_2H = 14,
    ITEM_TYPE_MACE_1H = 15,
    ITEM_TYPE_MACE_2H = 16,
    ITEM_TYPE_DAGGER = 17,
    ITEM_TYPE_SCEPTER = 18,
    ITEM_TYPE_RANGED_1H = 19,
    ITEM_TYPE_RANGED_2H = 20,
    ITEM_TYPE_SHIELD = 21,
    ITEM_TYPE_OFFHAND = 22,
    MAX_ITEM_TYPES = 23,
};

enum ItemTypeFlag : uint32_t
{
    ITEM_TYPE_FLAG_OTHER = 0,
    ITEM_TYPE_FLAG_HEAD = 1 << 0,
    ITEM_TYPE_FLAG_AMULET = 1 << 1,
    ITEM_TYPE_FLAG_CHEST = 1 << 2,
    ITEM_TYPE_FLAG_LEGS = 1 << 3,
    ITEM_TYPE_FLAG_FEET = 1 << 4,
    ITEM_TYPE_FLAG_RING = 1 << 5,
    ITEM_TYPE_FLAG_HANDS = 1 << 6,
    ITEM_TYPE_FLAG_BELT = 1 << 7,
    ITEM_TYPE_FLAG_SHOULDERS = 1 << 8,
    ITEM_TYPE_FLAG_MEDAL = 1 << 9,
    ITEM_TYPE_FLAG_SWORD_1H = 1 << 10,
    ITEM_TYPE_FLAG_SWORD_2H = 1 << 11,
    ITEM_TYPE_FLAG_AXE_1H = 1 << 12,
    ITEM_TYPE_FLAG_AXE_2H = 1 << 13,
    ITEM_TYPE_FLAG_MACE_1H = 1 << 14,
    ITEM_TYPE_FLAG_MACE_2H = 1 << 15,
    ITEM_TYPE_FLAG_DAGGER = 1 << 16,
    ITEM_TYPE_FLAG_FLAG_SCEPTER = 1 << 17,
    ITEM_TYPE_FLAG_RANGED_1H = 1 << 18,
    ITEM_TYPE_FLAG_RANGED_2H = 1 << 19,
    ITEM_TYPE_FLAG_SHIELD = 1 << 20,
    ITEM_TYPE_FLAG_OFFHAND = 1 << 21,
};

#endif//INC_GDCL_GAME_ITEM_TYPE_H