#ifndef INC_GDCL_DLL_ENGINE_API_GRAPHICS_ALIGN_H
#define INC_GDCL_DLL_ENGINE_API_GRAPHICS_ALIGN_H

namespace EngineAPI
{

enum GraphicsXAlign
{
    GRAPHICS_X_ALIGN_LEFT = 0,
    GRAPHICS_X_ALIGN_RIGHT = 1,
    GRAPHICS_X_ALIGN_CENTER = 2,
};

enum GraphicsYAlign
{
    GRAPHICS_Y_ALIGN_TOP = 0,
    GRAPHICS_Y_ALIGN_BOTTOM = 1,
    GRAPHICS_Y_ALIGN_CENTER = 2,
};

}

#endif//INC_GDCL_DLL_ENGINE_API_GRAPHICS_ALIGN_H